tasks:
  build-deps:
    runner: razorci/openjdk:11-buster
    steps:
    - checkout
    - commands:
      - |
        mvn clean install test -Dsuite=single.xml
        reports/html:
         dir: coverage
         index: index.html
